/*
# MindOS Learning Intelligence Engine — Core Schema

## Overview
This migration creates all tables required for the Learning Intelligence Engine:
Thinking History, Learning Sessions, Flashcards, Quizzes, Quiz Attempts,
Revisions, Notifications, Weak Areas, Recommendations, Hint Logs,
and Mock Interviews.

All tables are owner-scoped (user_id FK → auth.users) with RLS enabled.
Each table gets 4 CRUD policies scoped to authenticated owners.

## New Tables

### 1. learning_sessions
Append-only record of a focused study session for analytics.
- user_id, language_slug, topic_id, started_at, ended_at, duration_minutes, xp_gained

### 2. thinking_history
Heart of the problem-solving system — tracks every attempt at a problem.
- user_id, problem_id, started_at, finished_at, thinking_seconds, hints_opened, attempts, difficulty, solution_completed, revision_required, next_review_date, improvement_score

### 3. hint_logs
Records which progressive hint stages a user has revealed for a problem.
- user_id, thinking_history_id, stage (1-7), revealed_at

### 4. flashcards
Auto-generated and manual flashcards for spaced repetition.
- user_id, front, back, source_type (topic|note|mistake|bookmark), source_ref, language_slug, status (new|learning|known|mastered), ease_factor, interval_days, next_review_at

### 5. quizzes
Quiz definitions per topic/language.
- user_id (nullable for shared), language_slug, topic_slug, title, quiz_type (mcq|fill_blank|output_predict|code_debug|concept_match), questions (JSONB)

### 6. quiz_attempts
Records each quiz attempt with score and per-question results.
- user_id, quiz_id, score, total, answers (JSONB), passed, attempted_at

### 7. revisions
Spaced-repetition revision schedule (1/3/7/14/30 day intervals).
- user_id, topic_ref, language_slug, title, scheduled_date, interval_days, completed, completed_at, accuracy

### 8. notifications
Intelligent reminders generated by the engine.
- user_id, kind (revision|weak_topic|planner|goal|achievement), title, body, resource_url, read, created_at

### 9. weak_areas
Auto-detected weak areas based on learning behavior.
- user_id, language_slug, topic_ref, title, weakness_type (fail_rate|skip_rate|low_completion|low_quiz|high_hints|long_solve|missed_revision), severity, score, detected_at

### 10. recommendations
AI-powered next-step suggestions (mock/heuristic for now).
- user_id, kind (next_topic|next_language|revision|practice_problem|interview|project), title, subtitle, language_slug, priority, reason, accepted, created_at

### 11. mock_interviews
Interview mode sessions with Q&A flow and self-evaluation.
- user_id, track (python|java|sql|javascript|dsa|system_design), status (active|completed), questions (JSONB), current_index, started_at, completed_at, overall_score

### 12. achievements_log
Tracks achievement unlocks (complements existing user_achievements table).
- user_id, achievement_code, title, xp_reward, unlocked_at

## Security
- RLS enabled on every table.
- Each table has 4 owner-scoped policies (SELECT/INSERT/UPDATE/DELETE) using auth.uid() = user_id.
- user_id columns default to auth.uid() so inserts that omit user_id still work.
*/

-- 1. learning_sessions
CREATE TABLE IF NOT EXISTS learning_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  language_slug text,
  topic_id uuid,
  started_at timestamptz NOT NULL DEFAULT now(),
  ended_at timestamptz,
  duration_minutes integer NOT NULL DEFAULT 0,
  xp_gained integer NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_learning_sessions_user ON learning_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_learning_sessions_started ON learning_sessions(started_at);
ALTER TABLE learning_sessions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "select_own_learning_sessions" ON learning_sessions;
CREATE POLICY "select_own_learning_sessions" ON learning_sessions FOR SELECT TO authenticated USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "insert_own_learning_sessions" ON learning_sessions;
CREATE POLICY "insert_own_learning_sessions" ON learning_sessions FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "update_own_learning_sessions" ON learning_sessions;
CREATE POLICY "update_own_learning_sessions" ON learning_sessions FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "delete_own_learning_sessions" ON learning_sessions;
CREATE POLICY "delete_own_learning_sessions" ON learning_sessions FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- 2. thinking_history
CREATE TABLE IF NOT EXISTS thinking_history (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  problem_id uuid,
  problem_title text NOT NULL,
  language_slug text,
  started_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz,
  thinking_seconds integer NOT NULL DEFAULT 0,
  hints_opened integer NOT NULL DEFAULT 0,
  attempts integer NOT NULL DEFAULT 0,
  difficulty text NOT NULL DEFAULT 'Medium',
  solution_completed boolean NOT NULL DEFAULT false,
  revision_required boolean NOT NULL DEFAULT false,
  next_review_date date,
  improvement_score integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_thinking_history_user ON thinking_history(user_id);
CREATE INDEX IF NOT EXISTS idx_thinking_history_problem ON thinking_history(problem_id);
ALTER TABLE thinking_history ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "select_own_thinking_history" ON thinking_history;
CREATE POLICY "select_own_thinking_history" ON thinking_history FOR SELECT TO authenticated USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "insert_own_thinking_history" ON thinking_history;
CREATE POLICY "insert_own_thinking_history" ON thinking_history FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "update_own_thinking_history" ON thinking_history;
CREATE POLICY "update_own_thinking_history" ON thinking_history FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "delete_own_thinking_history" ON thinking_history;
CREATE POLICY "delete_own_thinking_history" ON thinking_history FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- 3. hint_logs
CREATE TABLE IF NOT EXISTS hint_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  thinking_history_id uuid REFERENCES thinking_history(id) ON DELETE CASCADE,
  stage integer NOT NULL,
  stage_name text NOT NULL,
  revealed_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_hint_logs_user ON hint_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_hint_logs_th ON hint_logs(thinking_history_id);
ALTER TABLE hint_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "select_own_hint_logs" ON hint_logs;
CREATE POLICY "select_own_hint_logs" ON hint_logs FOR SELECT TO authenticated USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "insert_own_hint_logs" ON hint_logs;
CREATE POLICY "insert_own_hint_logs" ON hint_logs FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "update_own_hint_logs" ON hint_logs;
CREATE POLICY "update_own_hint_logs" ON hint_logs FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "delete_own_hint_logs" ON hint_logs;
CREATE POLICY "delete_own_hint_logs" ON hint_logs FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- 4. flashcards
CREATE TABLE IF NOT EXISTS flashcards (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  front text NOT NULL,
  back text NOT NULL,
  source_type text NOT NULL DEFAULT 'topic',
  source_ref text,
  language_slug text,
  status text NOT NULL DEFAULT 'new',
  ease_factor real NOT NULL DEFAULT 2.5,
  interval_days integer NOT NULL DEFAULT 0,
  next_review_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_flashcards_user ON flashcards(user_id);
CREATE INDEX IF NOT EXISTS idx_flashcards_review ON flashcards(next_review_at);
ALTER TABLE flashcards ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "select_own_flashcards" ON flashcards;
CREATE POLICY "select_own_flashcards" ON flashcards FOR SELECT TO authenticated USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "insert_own_flashcards" ON flashcards;
CREATE POLICY "insert_own_flashcards" ON flashcards FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "update_own_flashcards" ON flashcards;
CREATE POLICY "update_own_flashcards" ON flashcards FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "delete_own_flashcards" ON flashcards;
CREATE POLICY "delete_own_flashcards" ON flashcards FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- 5. quizzes
CREATE TABLE IF NOT EXISTS quizzes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  language_slug text NOT NULL,
  topic_slug text,
  title text NOT NULL,
  quiz_type text NOT NULL DEFAULT 'mcq',
  questions jsonb NOT NULL DEFAULT '[]',
  is_published boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_quizzes_language ON quizzes(language_slug);
CREATE INDEX IF NOT EXISTS idx_quizzes_user ON quizzes(user_id);
ALTER TABLE quizzes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "select_quizzes" ON quizzes;
CREATE POLICY "select_quizzes" ON quizzes FOR SELECT TO authenticated USING (user_id IS NULL OR auth.uid() = user_id);
DROP POLICY IF EXISTS "insert_own_quizzes" ON quizzes;
CREATE POLICY "insert_own_quizzes" ON quizzes FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "update_own_quizzes" ON quizzes;
CREATE POLICY "update_own_quizzes" ON quizzes FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "delete_own_quizzes" ON quizzes;
CREATE POLICY "delete_own_quizzes" ON quizzes FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- 6. quiz_attempts
CREATE TABLE IF NOT EXISTS quiz_attempts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  quiz_id uuid REFERENCES quizzes(id) ON DELETE CASCADE,
  score integer NOT NULL DEFAULT 0,
  total integer NOT NULL DEFAULT 0,
  answers jsonb NOT NULL DEFAULT '[]',
  passed boolean NOT NULL DEFAULT false,
  attempted_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_quiz_attempts_user ON quiz_attempts(user_id);
ALTER TABLE quiz_attempts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "select_own_quiz_attempts" ON quiz_attempts;
CREATE POLICY "select_own_quiz_attempts" ON quiz_attempts FOR SELECT TO authenticated USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "insert_own_quiz_attempts" ON quiz_attempts;
CREATE POLICY "insert_own_quiz_attempts" ON quiz_attempts FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "update_own_quiz_attempts" ON quiz_attempts;
CREATE POLICY "update_own_quiz_attempts" ON quiz_attempts FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "delete_own_quiz_attempts" ON quiz_attempts;
CREATE POLICY "delete_own_quiz_attempts" ON quiz_attempts FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- 7. revisions
CREATE TABLE IF NOT EXISTS revisions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  topic_ref text NOT NULL,
  language_slug text NOT NULL,
  title text NOT NULL,
  scheduled_date date NOT NULL,
  interval_days integer NOT NULL DEFAULT 1,
  completed boolean NOT NULL DEFAULT false,
  completed_at timestamptz,
  accuracy integer,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_revisions_user ON revisions(user_id);
CREATE INDEX IF NOT EXISTS idx_revisions_date ON revisions(scheduled_date);
ALTER TABLE revisions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "select_own_revisions" ON revisions;
CREATE POLICY "select_own_revisions" ON revisions FOR SELECT TO authenticated USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "insert_own_revisions" ON revisions;
CREATE POLICY "insert_own_revisions" ON revisions FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "update_own_revisions" ON revisions;
CREATE POLICY "update_own_revisions" ON revisions FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "delete_own_revisions" ON revisions;
CREATE POLICY "delete_own_revisions" ON revisions FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- 8. notifications
CREATE TABLE IF NOT EXISTS notifications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  kind text NOT NULL,
  title text NOT NULL,
  body text,
  resource_url text,
  read boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_id);
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "select_own_notifications" ON notifications;
CREATE POLICY "select_own_notifications" ON notifications FOR SELECT TO authenticated USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "insert_own_notifications" ON notifications;
CREATE POLICY "insert_own_notifications" ON notifications FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "update_own_notifications" ON notifications;
CREATE POLICY "update_own_notifications" ON notifications FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "delete_own_notifications" ON notifications;
CREATE POLICY "delete_own_notifications" ON notifications FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- 9. weak_areas
CREATE TABLE IF NOT EXISTS weak_areas (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  language_slug text NOT NULL,
  topic_ref text,
  title text NOT NULL,
  weakness_type text NOT NULL,
  severity text NOT NULL DEFAULT 'medium',
  score real NOT NULL DEFAULT 0.5,
  detected_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_weak_areas_user ON weak_areas(user_id);
ALTER TABLE weak_areas ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "select_own_weak_areas" ON weak_areas;
CREATE POLICY "select_own_weak_areas" ON weak_areas FOR SELECT TO authenticated USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "insert_own_weak_areas" ON weak_areas;
CREATE POLICY "insert_own_weak_areas" ON weak_areas FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "update_own_weak_areas" ON weak_areas;
CREATE POLICY "update_own_weak_areas" ON weak_areas FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "delete_own_weak_areas" ON weak_areas;
CREATE POLICY "delete_own_weak_areas" ON weak_areas FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- 10. recommendations
CREATE TABLE IF NOT EXISTS recommendations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  kind text NOT NULL,
  title text NOT NULL,
  subtitle text,
  language_slug text,
  priority integer NOT NULL DEFAULT 5,
  reason text,
  accepted boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_recommendations_user ON recommendations(user_id);
ALTER TABLE recommendations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "select_own_recommendations" ON recommendations;
CREATE POLICY "select_own_recommendations" ON recommendations FOR SELECT TO authenticated USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "insert_own_recommendations" ON recommendations;
CREATE POLICY "insert_own_recommendations" ON recommendations FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "update_own_recommendations" ON recommendations;
CREATE POLICY "update_own_recommendations" ON recommendations FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "delete_own_recommendations" ON recommendations;
CREATE POLICY "delete_own_recommendations" ON recommendations FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- 11. mock_interviews
CREATE TABLE IF NOT EXISTS mock_interviews (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  track text NOT NULL,
  status text NOT NULL DEFAULT 'active',
  questions jsonb NOT NULL DEFAULT '[]',
  current_index integer NOT NULL DEFAULT 0,
  self_evaluations jsonb NOT NULL DEFAULT '[]',
  improvement_notes text,
  started_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  overall_score integer
);
CREATE INDEX IF NOT EXISTS idx_mock_interviews_user ON mock_interviews(user_id);
ALTER TABLE mock_interviews ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "select_own_mock_interviews" ON mock_interviews;
CREATE POLICY "select_own_mock_interviews" ON mock_interviews FOR SELECT TO authenticated USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "insert_own_mock_interviews" ON mock_interviews;
CREATE POLICY "insert_own_mock_interviews" ON mock_interviews FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "update_own_mock_interviews" ON mock_interviews;
CREATE POLICY "update_own_mock_interviews" ON mock_interviews FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "delete_own_mock_interviews" ON mock_interviews;
CREATE POLICY "delete_own_mock_interviews" ON mock_interviews FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- 12. achievements_log
CREATE TABLE IF NOT EXISTS achievements_log (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  achievement_code text NOT NULL,
  title text NOT NULL,
  xp_reward integer NOT NULL DEFAULT 0,
  unlocked_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_achievements_log_user ON achievements_log(user_id);
ALTER TABLE achievements_log ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "select_own_achievements_log" ON achievements_log;
CREATE POLICY "select_own_achievements_log" ON achievements_log FOR SELECT TO authenticated USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "insert_own_achievements_log" ON achievements_log;
CREATE POLICY "insert_own_achievements_log" ON achievements_log FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "update_own_achievements_log" ON achievements_log;
CREATE POLICY "update_own_achievements_log" ON achievements_log FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "delete_own_achievements_log" ON achievements_log;
CREATE POLICY "delete_own_achievements_log" ON achievements_log FOR DELETE TO authenticated USING (auth.uid() = user_id);
